apiVersion: v1
kind: Service
metadata:
  name: kubernetes-template
spec:
  selector:
    app: kubernetes-template
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
--- # Delimiter use to separate resources definitions
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-template
  template:
    metadata:
      labels:
        app: kubernetes-template
    spec:
      containers:
        - name: app
          image: <username>/kubernetes-template # Uploaded from DockerHub
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
            - name: MINIO_ACCESS_KEY
              value: mykey
            - name: MINIO_SECRET_KEY
              value: mysecret
            - name: MINIO_HOST
              value: minio
          imagePullPolicy: Always

